#!/bin/sh
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../../.." && pwd)
HERE="$ROOT/validation/iterative/real64_phase_a7"
RECEIPT="$HERE/phase_a7_implementation_receipt.sha256"
LC_ALL=C
export LC_ALL

(
  cd "$ROOT"
  shasum -a 256 -c "$RECEIPT" >/dev/null
)
echo "SPOR64 PHASE-A7 RECEIPT PASS"

PYTHONDONTWRITEBYTECODE=1 python3 "$HERE/check_phase_a7.py"
PYTHONPATH="$HERE" PYTHONDONTWRITEBYTECODE=1 python3 -m unittest -v \
  test_phase_a7_contract

echo "SPOR64 PHASE-A7 STATIC OWNERSHIP/ABI BLUEPRINT PASS"
echo "SPOR64 PHASE-A7 FORTRAN-COMPILATIONS=0 OBJECT-LINKS=0"
echo "SPOR64 PHASE-A7 OBJECT-EXECUTIONS=0 TRACKING-READS=0"
echo "SPOR64 PHASE-A7 TRANSPORT-APPLICATIONS=0 DRAGON-RUNS=0"
echo "SPOR64 PHASE-A7 RADIAL-CONVERGENCE=NOT-EVALUATED"
echo "SPOR64 PHASE-A7 OUTER-PICARD-CONVERGENCE=NOT-EVALUATED"
