*DECK SPOASM
      SUBROUTINE SPOASM(IPSYS,IPMACR,IPTRK,IPSNAP,IPBASIS,IFIXB,
     1 IMPX,RANK_POD)
*
*-----------------------------------------------------------------------
*
*Purpose:
* Assemble the radial POD trial space used by the axial SPOD solve.
* RANK_POD is the number of retained axial modes; zero keeps the full
* numerical snapshot rank. IFIXB=1 copies the POD trial space from the
* read-only IPBASIS system while rebuilding the current radial response.
*
*-----------------------------------------------------------------------
      USE GANLIB
      USE SPOT_LEAKAGE, ONLY: SPOLE2,SPOF00,SPOQ00,SPOQFS
      USE IEEE_ARITHMETIC, ONLY: IEEE_IS_FINITE
      TYPE(C_PTR) IPSYS,IPMACR,IPTRK,IPSNAP,IPBASIS
      INTEGER IFIXB,IMPX,RANK_POD
      PARAMETER(NSTATE=40,IOUT=6)
      INTEGER IPAR(NSTATE),ISTATE(NSTATE),NMODE,IRMIN,IRMAX
      INTEGER NPHYS_S0,NIFIS,NSCAT,IFSMARK,NFS_SNAP
      INTEGER REMOVAL_SNAP,REMOVAL_GROUP,REMOVAL_MIX
      REAL REMOVAL,REMOVAL_MIN,KEFF_S
      DOUBLE PRECISION REC_ERR,ORTHO_ERR,RBAL,RSCALE,RBAL_MAX,DLAG
      DOUBLE PRECISION QLAG_NUM,QLAG_DEN,QLAG_ABS,QSCALE,QLAG_L2,
     1 QLAG_MAX
      TYPE(C_PTR) JPSNAP1,JPSNAP2,JPSNAP3,JPSNAP4,KPSNAP,LPSNAP
      TYPE(C_PTR) MPSNAP,IPFLUX,IPSOUR,JPSYS,KPSYS,IPLIB,IPMACR2
      TYPE(C_PTR) JPMACR2,KPMACR2,JPQFISS,KPQFISS
      TYPE(C_PTR) JPBASIS,KPBASIS
      CHARACTER HSMG*131,HSIGN*12,BTYPE*12
*
      INTEGER, ALLOCATABLE, DIMENSION(:) :: IDL2D,MAT2D,POD_RANK
      INTEGER, ALLOCATABLE, DIMENSION(:) :: FS_MODE
      INTEGER, ALLOCATABLE, DIMENSION(:) :: NJJS,IJJS,IPOS
      REAL, ALLOCATABLE, DIMENSION(:) :: VOL2D,VOLREG,VOLREF,TXSC2D,
     1 LEAK1D
      REAL, ALLOCATABLE, DIMENSION(:) :: SCAT,QREG,QFREG
      REAL, ALLOCATABLE, DIMENSION(:,:) :: SXSC2D,TXSC,BASIS,COEFF
      REAL, ALLOCATABLE, DIMENSION(:,:) :: REGFLUX,CHI
      REAL, ALLOCATABLE, DIMENSION(:,:) :: COEFP
      REAL, ALLOCATABLE, DIMENSION(:,:,:) :: SXSC,FLUX2D,SOUR2D,
     1 QFISS2D,PHIRK,DB2,NUSIGF
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:) :: SIGMA
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:,:) :: POD_SIG,FISPROD
*
*  RECOVER TRACKING AND SNAPSHOT DIMENSIONS.
      CALL LCMGET(IPTRK,'STATE-VECTOR',IPAR)
      NREG=IPAR(1)
      NUNKN=IPAR(2)
      NMIX=IPAR(4)
      NREG2D=IPAR(6)
      ISCAT=IPAR(16)
      ALLOCATE(IDL2D(NREG),MAT2D(NREG),VOL2D(NREG),VOLREG(NREG2D))
      CALL LCMGET(IPSNAP,'LISTDIM',NSNAP)
      JPSNAP1=LCMGID(IPSNAP,'TRACK')
      NUNK2D=0
      NMIX2D=0
      IBIHET=0
      DO ISNAP=1,NSNAP
        KPSNAP=LCMGIL(JPSNAP1,ISNAP)
        CALL LCMGET(KPSNAP,'STATE-VECTOR',IPAR)
        NMIX2D=MAX(NMIX2D,IPAR(4))
        IF(NREG2D.NE.IPAR(1)) CALL XABORT(
     1    'SPOASM: INCONSISTENT SNAPSHOT REGION COUNT.')
        IF(ISNAP.EQ.1) THEN
          NUNK2D=IPAR(2)
          IBIHET=IPAR(40)
        ELSE IF((NUNK2D.NE.IPAR(2)).OR.(IBIHET.NE.IPAR(40))) THEN
          CALL XABORT('SPOASM: INCONSISTENT SNAPSHOT TRACKING.')
        ENDIF
      ENDDO
      IF(NMIX2D*NSNAP.NE.NMIX) CALL XABORT(
     1  'SPOASM: INCONSISTENT SNAPSHOT MIXTURES.')
*
*  RECOVER MACROLIB DIMENSIONS.
      CALL LCMGET(IPMACR,'STATE-VECTOR',IPAR)
      NGRP=IPAR(1)
      MAXMIX=IPAR(2)
      NANIS=IPAR(3)
      IF((IFIXB.NE.0).AND.(IFIXB.NE.1)) CALL XABORT(
     1  'SPOASM: INVALID FIXED-BASIS FLAG.')
      IF(IFIXB.EQ.1) THEN
        IF(.NOT.C_ASSOCIATED(IPBASIS)) CALL XABORT(
     1    'SPOASM: MISSING FIXED-BASIS OBJECT.')
        IF(RANK_POD.LE.0) CALL XABORT(
     1    'SPOASM: FIXED BASIS REQUIRES POSITIVE RANK.')
        CALL LCMGTC(IPBASIS,'SIGNATURE',12,HSIGN)
        IF(HSIGN.NE.'L_PIJ') CALL XABORT(
     1    'SPOASM: FIXED-BASIS OBJECT IS NOT L_PIJ.')
        CALL LCMGET(IPBASIS,'STATE-VECTOR',IPAR)
        IF((IPAR(8).NE.NGRP).OR.(IPAR(9).NE.NUNKN)) CALL XABORT(
     1    'SPOASM: FIXED-BASIS SYSTEM DIMENSION MISMATCH.')
        CALL LCMLEN(IPBASIS,'GROUP',ILONG,ITYLCM)
        IF((ILONG.NE.NGRP).OR.(ITYLCM.NE.10)) CALL XABORT(
     1    'SPOASM: INVALID FIXED-BASIS GROUP LIST.')
        CALL LCMLEN(IPBASIS,'POD-RANK-G',ILONG,ITYLCM)
        IF((ILONG.NE.NGRP).OR.(ITYLCM.NE.1)) CALL XABORT(
     1    'SPOASM: INVALID FIXED-BASIS RANK RECORD.')
        CALL LCMLEN(IPBASIS,'POD-SIGMA-G',ILONG,ITYLCM)
        IF((ILONG.NE.NSNAP*NGRP).OR.(ITYLCM.NE.4)) CALL XABORT(
     1    'SPOASM: INVALID FIXED-BASIS SIGMA RECORD.')
        JPBASIS=LCMGID(IPBASIS,'GROUP')
        ALLOCATE(VOLREF(NREG2D))
      ENDIF
      IF(NMIX.GT.MAXMIX) THEN
        WRITE(HSMG,'(45HSPOASM: THE NUMBER OF MIXTURES IN THE TRACKIN,
     1  3HG (,I5,49H) IS GREATER THAN THE NUMBER OF MIXTURES IN THE M,
     2  9HACROLIB (,I5,2H).)') NMIX,MAXMIX
        CALL XABORT(HSMG)
      ENDIF
*
*  RECOVER SCALAR-FLUX SNAPSHOTS.
      JPSNAP3=LCMGID(IPSNAP,'FLUX')
      MAXK2D=0
      DO ISNAP=1,NSNAP
        KPSNAP=LCMGIL(JPSNAP3,ISNAP)
        IPFLUX=LCMGID(KPSNAP,'FLUX')
        CALL LCMLEL(IPFLUX,1,ILONG,ITYLCM)
        MAXK2D=MAX(MAXK2D,ILONG)
      ENDDO
      ALLOCATE(FLUX2D(MAXK2D,NSNAP,NGRP))
      ALLOCATE(SOUR2D(MAXK2D,NSNAP,NGRP))
      ALLOCATE(QFISS2D(MAXK2D,NSNAP,NGRP),FS_MODE(NSNAP))
      FLUX2D=0.0
      SOUR2D=0.0
      QFISS2D=0.0
      FS_MODE=0
      DO ISNAP=1,NSNAP
        KPSNAP=LCMGIL(JPSNAP3,ISNAP)
        IPFLUX=LCMGID(KPSNAP,'FLUX')
        IPSOUR=LCMGID(KPSNAP,'SOUR')
        CALL LCMLEN(KPSNAP,'SPOT-FS-EQN',ILONG,ITYLCM)
        IF(ILONG.NE.0) THEN
          IF((ILONG.NE.1).OR.(ITYLCM.NE.1)) CALL XABORT(
     1      'SPOASM: INVALID FIXED-SOURCE EQUATION MARKER.')
          CALL LCMGET(KPSNAP,'SPOT-FS-EQN',IFSMARK)
          IF(IFSMARK.NE.1) CALL XABORT(
     1      'SPOASM: UNKNOWN FIXED-SOURCE EQUATION MARKER.')
          CALL LCMLEN(KPSNAP,'SPOT-QFISS',ILONG,ITYLCM)
          IF((ILONG.NE.1).OR.(ITYLCM.NE.10)) CALL XABORT(
     1      'SPOASM: INVALID FROZEN FISSION SOURCE LIST.')
          JPQFISS=LCMGID(KPSNAP,'SPOT-QFISS')
          KPQFISS=LCMGIL(JPQFISS,1)
          FS_MODE(ISNAP)=1
        ENDIF
        DO IGR=1,NGRP
          CALL LCMGDL(IPFLUX,IGR,FLUX2D(1,ISNAP,IGR))
          CALL LCMGDL(IPSOUR,IGR,SOUR2D(1,ISNAP,IGR))
          IF(FS_MODE(ISNAP).EQ.1) THEN
            CALL LCMLEL(KPQFISS,IGR,ILONG,ITYLCM)
            IF((ILONG.NE.MAXK2D).OR.(ITYLCM.NE.2)) CALL XABORT(
     1        'SPOASM: INVALID FROZEN FISSION SOURCE ITEM.')
            CALL LCMGDL(KPQFISS,IGR,QFISS2D(1,ISNAP,IGR))
          ENDIF
        ENDDO
      ENDDO
      NFS_SNAP=SUM(FS_MODE)
      IF((NFS_SNAP.NE.0).AND.(NFS_SNAP.NE.NSNAP)) CALL XABORT(
     1  'SPOASM: MIXED EIGENVALUE AND FIXED-SOURCE SNAPSHOTS.')
*
*  MAP REGIONAL FLUXES AND SNAPSHOT-SPECIFIC MATERIAL BLOCKS.
      ALLOCATE(TXSC(0:MAXMIX,NGRP),SXSC(0:MAXMIX,NANIS,NGRP))
      ALLOCATE(PHIRK(NREG2D,NSNAP,NGRP),DB2(NREG2D,NSNAP,NGRP))
      TXSC=0.0
      SXSC=0.0
      PHIRK=0.0
      DB2=0.0
      VOLREG=0.0
      NPHYS_S0=0
      RBAL_MAX=0.0D0
      QLAG_NUM=0.0D0
      QLAG_DEN=0.0D0
      QLAG_ABS=0.0D0
      QSCALE=0.0D0
      REMOVAL_MIN=HUGE(REMOVAL_MIN)
      REMOVAL_SNAP=0
      REMOVAL_GROUP=0
      REMOVAL_MIX=0
      JPSNAP2=LCMGID(IPSNAP,'SYSTEM')
      JPSNAP4=LCMGID(IPSNAP,'MICROLIB2')
      ALLOCATE(LEAK1D(NGRP))
      DO ISNAP=1,NSNAP
        KPSNAP=LCMGIL(JPSNAP3,ISNAP)
        CALL LCMLEN(KPSNAP,'SPOT-LEAK1D',ILONG,ITYLCM)
        IF(ILONG.EQ.0) THEN
          LEAK1D=0.0
        ELSE IF(ILONG.EQ.NGRP) THEN
          CALL LCMGET(KPSNAP,'SPOT-LEAK1D',LEAK1D)
        ELSE
          CALL XABORT('SPOASM: INVALID SPOT-LEAK1D LENGTH.')
        ENDIF
        KPSNAP=LCMGIL(JPSNAP1,ISNAP)
        CALL LCMGET(KPSNAP,'KEYFLX',IDL2D)
        CALL LCMGET(KPSNAP,'MATCOD',MAT2D)
        CALL LCMGET(KPSNAP,'VOLUME',VOL2D)
        DO I=1,NREG2D
          IF((.NOT.IEEE_IS_FINITE(VOL2D(I))).OR.
     1       (VOL2D(I).LE.0.0)) THEN
            CALL XABORT('SPOASM: INVALID SNAPSHOT VOLUME.')
          ENDIF
          IF(ISNAP.EQ.1) THEN
            VOLREG(I)=VOL2D(I)
          ELSE IF(TRANSFER(VOL2D(I),0).NE.
     1            TRANSFER(VOLREG(I),0)) THEN
            CALL XABORT('SPOASM: SNAPSHOT VOLUME MISMATCH.')
          ENDIF
        ENDDO
*       MAP EVERY FINAL-GROUP FLUX BEFORE RE-EVALUATING THE MULTIGROUP RHS.
        ALLOCATE(REGFLUX(NREG2D,NGRP),QREG(NREG2D),QFREG(NREG2D))
        REGFLUX=0.0
        DO I=1,NREG2D
          IBM=MAT2D(I)
          IF((IBM.LT.0).OR.(IBM.GT.NMIX2D)) CALL XABORT(
     1      'SPOASM: SNAPSHOT MATERIAL INDEX OVERFLOW.')
          IUNK=IDL2D(I)
          IF(IUNK.EQ.0) CYCLE
          IF((IUNK.LT.1).OR.(IUNK.GT.MAXK2D)) CALL XABORT(
     1      'SPOASM: SNAPSHOT SCALAR KEY OVERFLOW.')
          DO IGR=1,NGRP
            REGFLUX(I,IGR)=FLUX2D(IUNK,ISNAP,IGR)
            PHIRK(I,ISNAP,IGR)=REGFLUX(I,IGR)
            IF((.NOT.IEEE_IS_FINITE(REGFLUX(I,IGR))).OR.
     1         (REGFLUX(I,IGR).LE.0.0)) CALL XABORT(
     2        'SPOASM: ACTIVE FLUX MUST BE FINITE AND POSITIVE.')
          ENDDO
        ENDDO
*
*       EIGENVALUE SNAPSHOTS USE THEIR FINAL-STATE PHYSICAL SOURCE.
*       ONLINE FIXED-SOURCE SNAPSHOTS INSTEAD KEEP THE EXACT FROZEN
*       FISSION SOURCE THAT WAS APPLIED BY THEIR RADIAL EQUATION.
        KPSNAP=LCMGIL(JPSNAP3,ISNAP)
        IF(FS_MODE(ISNAP).EQ.0) THEN
          CALL LCMLEN(KPSNAP,'K-EFFECTIVE',ILONG,ITYLCM)
          IF((ILONG.NE.1).OR.(ITYLCM.NE.2)) CALL XABORT(
     1      'SPOASM: INVALID SNAPSHOT EIGENVALUE RECORD.')
          CALL LCMGET(KPSNAP,'K-EFFECTIVE',KEFF_S)
        ELSE
          CALL LCMLEN(KPSNAP,'SPOT-FS-K',ILONG,ITYLCM)
          IF((ILONG.NE.1).OR.(ITYLCM.NE.2)) CALL XABORT(
     1      'SPOASM: INVALID FIXED-SOURCE EIGENVALUE RECORD.')
          CALL LCMGET(KPSNAP,'SPOT-FS-K',KEFF_S)
        ENDIF
        IF((.NOT.IEEE_IS_FINITE(KEFF_S)).OR.(KEFF_S.LE.0.0))
     1    CALL XABORT('SPOASM: INVALID SNAPSHOT EIGENVALUE.')
        IPLIB=LCMGIL(JPSNAP4,ISNAP)
        IPMACR2=LCMGID(IPLIB,'MACROLIB')
        CALL LCMGET(IPMACR2,'STATE-VECTOR',IPAR)
        NIFIS=IPAR(4)
        IF((IPAR(1).NE.NGRP).OR.(IPAR(2).NE.NMIX2D).OR.
     1     (NIFIS.LE.0)) CALL XABORT(
     2    'SPOASM: INCONSISTENT SNAPSHOT MACROLIB.')
        JPMACR2=LCMGID(IPMACR2,'GROUP')
        ALLOCATE(NUSIGF(NMIX2D,NIFIS,NGRP),CHI(NMIX2D,NIFIS))
        ALLOCATE(FISPROD(NREG2D,NIFIS))
        ALLOCATE(NJJS(NMIX2D),IJJS(NMIX2D),IPOS(NMIX2D))
        DO IGR=1,NGRP
          KPMACR2=LCMGIL(JPMACR2,IGR)
          CALL LCMLEN(KPMACR2,'NUSIGF',ILONG,ITYLCM)
          IF((ILONG.NE.NMIX2D*NIFIS).OR.(ITYLCM.NE.2))
     1      CALL XABORT('SPOASM: INVALID NUSIGF RECORD.')
          CALL LCMGET(KPMACR2,'NUSIGF',NUSIGF(1,1,IGR))
        ENDDO
        IF(FS_MODE(ISNAP).EQ.0) THEN
          CALL SPOF00(NREG2D,NGRP,NMIX2D,NIFIS,MAT2D,REGFLUX,
     1      NUSIGF,FISPROD)
        ELSE
          FISPROD=0.0D0
        ENDIF
*
        KPSNAP=LCMGIL(JPSNAP2,ISNAP)
        CALL LCMGET(KPSNAP,'STATE-VECTOR',IPAR)
        IF((NGRP.NE.IPAR(8)).OR.(NUNK2D.NE.IPAR(9))) CALL XABORT(
     1    'SPOASM: INCONSISTENT SNAPSHOT SYSTEM.')
        LPSNAP=LCMGID(KPSNAP,'GROUP')
        DO IGR=1,NGRP
          KPMACR2=LCMGIL(JPMACR2,IGR)
          CALL LCMLEN(KPMACR2,'CHI',ILONG,ITYLCM)
          IF((ILONG.NE.NMIX2D*NIFIS).OR.(ITYLCM.NE.2))
     1      CALL XABORT('SPOASM: INVALID CHI RECORD.')
          CALL LCMGET(KPMACR2,'CHI',CHI)
          CALL LCMLEN(KPMACR2,'NJJS00',ILONG,ITYLCM)
          IF((ILONG.NE.NMIX2D).OR.(ITYLCM.NE.1))
     1      CALL XABORT('SPOASM: INVALID NJJS00 RECORD.')
          CALL LCMGET(KPMACR2,'NJJS00',NJJS)
          CALL LCMLEN(KPMACR2,'IJJS00',ILONG,ITYLCM)
          IF((ILONG.NE.NMIX2D).OR.(ITYLCM.NE.1))
     1      CALL XABORT('SPOASM: INVALID IJJS00 RECORD.')
          CALL LCMGET(KPMACR2,'IJJS00',IJJS)
          CALL LCMLEN(KPMACR2,'IPOS00',ILONG,ITYLCM)
          IF((ILONG.NE.NMIX2D).OR.(ITYLCM.NE.1))
     1      CALL XABORT('SPOASM: INVALID IPOS00 RECORD.')
          CALL LCMGET(KPMACR2,'IPOS00',IPOS)
          CALL LCMLEN(KPMACR2,'SCAT00',NSCAT,ITYLCM)
          IF((NSCAT.LE.0).OR.(ITYLCM.NE.2))
     1      CALL XABORT('SPOASM: INVALID SCAT00 RECORD.')
          ALLOCATE(SCAT(NSCAT))
          CALL LCMGET(KPMACR2,'SCAT00',SCAT)
          IF(FS_MODE(ISNAP).EQ.0) THEN
            CALL SPOQ00(NREG2D,NGRP,NMIX2D,NIFIS,IGR,MAT2D,
     1        REGFLUX,KEFF_S,NJJS,IJJS,IPOS,SCAT,CHI,NUSIGF,QREG,
     2        FISPROD)
          ELSE
            QFREG=0.0
            DO I=1,NREG2D
              IUNK=IDL2D(I)
              IF(IUNK.GT.0) QFREG(I)=QFISS2D(IUNK,ISNAP,IGR)
            ENDDO
            CALL SPOQFS(NREG2D,NGRP,NMIX2D,IGR,MAT2D,REGFLUX,
     1        NJJS,IJJS,IPOS,SCAT,QFREG,QREG)
          ENDIF
*
          RBAL=0.0D0
          RSCALE=0.0D0
          ALLOCATE(TXSC2D(0:NMIX2D),SXSC2D(0:NMIX2D,NANIS))
          MPSNAP=LCMGIL(LPSNAP,IGR)
          CALL LCMGET(MPSNAP,'DRAGON-TXSC',TXSC2D)
          CALL LCMGET(MPSNAP,'DRAGON-S0XSC',SXSC2D)
          CALL LCMLEN(MPSNAP,'SPOT-S0-PHYS',ILONG,ITYLCM)
          IF(ILONG.EQ.NMIX2D+1) THEN
            CALL LCMGET(MPSNAP,'SPOT-S0-PHYS',SXSC2D(0,1))
            NPHYS_S0=NPHYS_S0+1
          ELSE IF(ILONG.NE.0) THEN
            CALL XABORT('SPOASM: INVALID SPOT-S0-PHYS LENGTH.')
          ENDIF
          DO IBM=1,NMIX2D
            REMOVAL=TXSC2D(IBM)-SXSC2D(IBM,1)+LEAK1D(IGR)
            IF(REMOVAL.LT.REMOVAL_MIN) THEN
              REMOVAL_MIN=REMOVAL
              REMOVAL_SNAP=ISNAP
              REMOVAL_GROUP=IGR
              REMOVAL_MIX=IBM
            ENDIF
          ENDDO
          IF(ISNAP.EQ.1) THEN
            TXSC(0,IGR)=TXSC2D(0)
            SXSC(0,:NANIS,IGR)=SXSC2D(0,:NANIS)
          ENDIF
          DO IBM=1,NMIX2D
            IMAT=(ISNAP-1)*NMIX2D+IBM
            TXSC(IMAT,IGR)=TXSC2D(IBM)
            SXSC(IMAT,:NANIS,IGR)=SXSC2D(IBM,:NANIS)
          ENDDO
          DO I=1,NREG2D
            IUNK=IDL2D(I)
            IF(IUNK.EQ.0) CYCLE
            IBM=MAT2D(I)
            DB2(I,ISNAP,IGR)=SPOLE2(TXSC2D(IBM),SXSC2D(IBM,1),
     1        QREG(I),PHIRK(I,ISNAP,IGR),LEAK1D(IGR))
            IF(.NOT.IEEE_IS_FINITE(DB2(I,ISNAP,IGR))) CALL XABORT(
     1        'SPOASM: NON-FINITE RADIAL OPERATOR.')
            DLAG=DBLE(QREG(I))-DBLE(SOUR2D(IUNK,ISNAP,IGR))
            QLAG_NUM=QLAG_NUM+DBLE(VOL2D(I))*DLAG*DLAG
            QLAG_DEN=QLAG_DEN+DBLE(VOL2D(I))*DBLE(QREG(I))*
     1        DBLE(QREG(I))
            QLAG_ABS=MAX(QLAG_ABS,ABS(DLAG))
            QSCALE=MAX(QSCALE,ABS(DBLE(QREG(I))))
            RBAL=RBAL+DBLE(VOL2D(I))*DBLE(DB2(I,ISNAP,IGR))*
     1        DBLE(PHIRK(I,ISNAP,IGR))
            RSCALE=RSCALE+DBLE(VOL2D(I))*(
     1        ABS(DBLE(TXSC2D(IBM)*PHIRK(I,ISNAP,IGR)))+
     2        ABS(DBLE(SXSC2D(IBM,1)*PHIRK(I,ISNAP,IGR)))+
     3        ABS(DBLE(QREG(I)))+
     4        ABS(DBLE(LEAK1D(IGR)*PHIRK(I,ISNAP,IGR))))
          ENDDO
          IF((.NOT.IEEE_IS_FINITE(RBAL)).OR.
     1       (.NOT.IEEE_IS_FINITE(RSCALE))) CALL XABORT(
     2      'SPOASM: NON-FINITE RADIAL BALANCE.')
          IF(RSCALE.GT.0.0D0) RBAL_MAX=MAX(RBAL_MAX,
     1      ABS(RBAL)/RSCALE)
          DEALLOCATE(SXSC2D,TXSC2D,SCAT)
        ENDDO
        DEALLOCATE(FISPROD,IPOS,IJJS,NJJS,CHI,NUSIGF)
        DEALLOCATE(QFREG,QREG,REGFLUX)
      ENDDO
      IF(ANY(.NOT.IEEE_IS_FINITE(PHIRK))) CALL XABORT(
     1  'SPOASM: NON-FINITE PHIRK ARRAY.')
      IF(ANY(.NOT.IEEE_IS_FINITE(DB2))) CALL XABORT(
     1  'SPOASM: NON-FINITE DB2 ARRAY.')
      IF((QLAG_DEN.LE.0.0D0).OR.(QSCALE.LE.0.0D0)) CALL XABORT(
     1  'SPOASM: INVALID FINAL-SOURCE DIAGNOSTIC SCALE.')
      QLAG_L2=SQRT(QLAG_NUM/QLAG_DEN)
      QLAG_MAX=QLAG_ABS/QSCALE
      IF((.NOT.IEEE_IS_FINITE(QLAG_L2)).OR.
     1   (.NOT.IEEE_IS_FINITE(QLAG_MAX))) CALL XABORT(
     2  'SPOASM: NON-FINITE FINAL-SOURCE DIAGNOSTIC.')
*
*  BUILD AND STORE ONE POD TRIAL SPACE PER ENERGY GROUP.
      ISTATE(:NSTATE)=0
      ISTATE(1)=1
      ISTATE(2)=1
      ISTATE(3)=1
      ISTATE(5)=1
      ISTATE(6)=1
      ISTATE(8)=NGRP
      ISTATE(9)=NUNKN
      ISTATE(10)=MAXMIX
      ISTATE(11)=ISCAT
      ISTATE(14)=1
      CALL LCMPUT(IPSYS,'STATE-VECTOR',NSTATE,1,ISTATE)
      JPSYS=LCMLID(IPSYS,'GROUP',NGRP)
      ALLOCATE(SIGMA(NSNAP),POD_RANK(NGRP),POD_SIG(NSNAP,NGRP))
      ALLOCATE(BASIS(NREG2D,NSNAP),COEFF(NSNAP,NSNAP))
      POD_SIG=0.0D0
      DO IGR=1,NGRP
        KPSYS=LCMDIL(JPSYS,IGR)
        IF(IFIXB.EQ.0) THEN
          CALL SPOPOD(NREG2D,NSNAP,PHIRK(1,1,IGR),VOLREG,RANK_POD,
     1      NMODE,BASIS,COEFF,SIGMA,REC_ERR,ORTHO_ERR,IMPX,IGR)
          ALLOCATE(COEFP(NMODE,NSNAP))
          DO ISNAP=1,NSNAP
            COEFP(:,ISNAP)=COEFF(:NMODE,ISNAP)
          ENDDO
        ELSE
          KPBASIS=LCMGIL(JPBASIS,IGR)
          CALL LCMLEN(KPBASIS,'NREG2D',ILONG,ITYLCM)
          IF((ILONG.NE.1).OR.(ITYLCM.NE.1)) CALL XABORT(
     1      'SPOASM: INVALID FIXED-BASIS NREG2D RECORD.')
          CALL LCMGET(KPBASIS,'NREG2D',I)
          IF(I.NE.NREG2D) CALL XABORT(
     1      'SPOASM: FIXED-BASIS RADIAL DIMENSION MISMATCH.')
          CALL LCMLEN(KPBASIS,'NSNAP',ILONG,ITYLCM)
          IF((ILONG.NE.1).OR.(ITYLCM.NE.1)) CALL XABORT(
     1      'SPOASM: INVALID FIXED-BASIS NSNAP RECORD.')
          CALL LCMGET(KPBASIS,'NSNAP',I)
          IF(I.NE.NSNAP) CALL XABORT(
     1      'SPOASM: FIXED-BASIS SNAPSHOT DIMENSION MISMATCH.')
          CALL LCMLEN(KPBASIS,'POD-NMODE',ILONG,ITYLCM)
          IF((ILONG.NE.1).OR.(ITYLCM.NE.1)) CALL XABORT(
     1      'SPOASM: INVALID FIXED-BASIS MODE RECORD.')
          CALL LCMGET(KPBASIS,'POD-NMODE',NMODE)
          IF(NMODE.NE.RANK_POD) CALL XABORT(
     1      'SPOASM: FIXED-BASIS MODE COUNT DOES NOT MATCH RANK.')
          CALL LCMLEN(KPBASIS,'VOL2D',ILONG,ITYLCM)
          IF((ILONG.NE.NREG2D).OR.(ITYLCM.NE.2)) CALL XABORT(
     1      'SPOASM: INVALID FIXED-BASIS VOLUME RECORD.')
          CALL LCMGET(KPBASIS,'VOL2D',VOLREF)
          DO I=1,NREG2D
            IF(TRANSFER(VOLREF(I),0).NE.TRANSFER(VOLREG(I),0))
     1        CALL XABORT('SPOASM: FIXED-BASIS VOLUME MISMATCH.')
          ENDDO
          CALL LCMLEN(KPBASIS,'POD-BASIS',ILONG,ITYLCM)
          IF((ILONG.NE.NREG2D*NMODE).OR.(ITYLCM.NE.2))
     1      CALL XABORT('SPOASM: INVALID FIXED POD BASIS.')
          CALL LCMGET(KPBASIS,'POD-BASIS',BASIS)
          ALLOCATE(COEFP(NMODE,NSNAP))
          CALL LCMLEN(KPBASIS,'POD-COEFF',ILONG,ITYLCM)
          IF((ILONG.NE.NMODE*NSNAP).OR.(ITYLCM.NE.2))
     1      CALL XABORT('SPOASM: INVALID FIXED POD COEFFICIENTS.')
          CALL LCMGET(KPBASIS,'POD-COEFF',COEFP)
          CALL LCMLEN(KPBASIS,'POD-SIGMA',ILONG,ITYLCM)
          IF((ILONG.NE.NSNAP).OR.(ITYLCM.NE.4))
     1      CALL XABORT('SPOASM: INVALID FIXED POD SINGULAR VALUES.')
          CALL LCMGET(KPBASIS,'POD-SIGMA',SIGMA)
          CALL LCMLEN(KPBASIS,'POD-REC-ERR',ILONG,ITYLCM)
          IF((ILONG.NE.1).OR.(ITYLCM.NE.4)) CALL XABORT(
     1      'SPOASM: INVALID FIXED POD RECONSTRUCTION RECORD.')
          CALL LCMGET(KPBASIS,'POD-REC-ERR',REC_ERR)
          CALL LCMLEN(KPBASIS,'POD-ORTHO',ILONG,ITYLCM)
          IF((ILONG.NE.1).OR.(ITYLCM.NE.4)) CALL XABORT(
     1      'SPOASM: INVALID FIXED POD ORTHOGONALITY RECORD.')
          CALL LCMGET(KPBASIS,'POD-ORTHO',ORTHO_ERR)
          IF(ANY(.NOT.IEEE_IS_FINITE(BASIS(:,:NMODE))).OR.
     1       ANY(.NOT.IEEE_IS_FINITE(COEFP)).OR.
     2       ANY(.NOT.IEEE_IS_FINITE(SIGMA)).OR.
     3       (.NOT.IEEE_IS_FINITE(REC_ERR)).OR.
     4       (.NOT.IEEE_IS_FINITE(ORTHO_ERR))) CALL XABORT(
     5      'SPOASM: NON-FINITE FIXED POD DATA.')
        ENDIF
        POD_RANK(IGR)=NMODE
        POD_SIG(:,IGR)=SIGMA
        CALL LCMPUT(KPSYS,'DRAGON-TXSC',MAXMIX+1,2,TXSC(0,IGR))
        CALL LCMPUT(KPSYS,'DRAGON-S0XSC',(MAXMIX+1)*NANIS,2,
     1    SXSC(0,1,IGR))
        CALL LCMPUT(KPSYS,'NREG2D',1,1,NREG2D)
        CALL LCMPUT(KPSYS,'NSNAP',1,1,NSNAP)
        CALL LCMPUT(KPSYS,'POD-NMODE',1,1,NMODE)
        CALL LCMPUT(KPSYS,'VOL2D',NREG2D,2,VOLREG)
        CALL LCMPUT(KPSYS,'POD-BASIS',NREG2D*NMODE,2,BASIS)
        CALL LCMPUT(KPSYS,'POD-COEFF',NMODE*NSNAP,2,COEFP)
        CALL LCMPUT(KPSYS,'RADIAL-OP',NREG2D*NSNAP,2,DB2(1,1,IGR))
        CALL LCMPUT(KPSYS,'POD-SIGMA',NSNAP,4,SIGMA)
        CALL LCMPUT(KPSYS,'POD-REC-ERR',1,4,REC_ERR)
        CALL LCMPUT(KPSYS,'POD-ORTHO',1,4,ORTHO_ERR)
        DEALLOCATE(COEFP)
      ENDDO
      CALL LCMPUT(IPSYS,'POD-RANK-G',NGRP,1,POD_RANK)
      CALL LCMPUT(IPSYS,'POD-SIGMA-G',NSNAP*NGRP,4,POD_SIG)
      CALL LCMPUT(IPSYS,'SPOT-FIXB',1,1,IFIXB)
      IF(IFIXB.EQ.1) THEN
        BTYPE='POD-FIXED'
      ELSE
        BTYPE='POD-BUILT'
      ENDIF
      CALL LCMPTC(IPSYS,'SPOT-BTYPE',12,BTYPE)
      IF(IMPX.GE.1) THEN
        IRMIN=MINVAL(POD_RANK)
        IRMAX=MAXVAL(POD_RANK)
        WRITE(IOUT,200) NGRP,IRMIN,IRMAX,NSNAP
      ENDIF
      IF(IMPX.GE.1.AND.NPHYS_S0.GT.0) WRITE(IOUT,220) NPHYS_S0
      CALL LCMPUT(IPSYS,'SPOT-RBAL',1,4,RBAL_MAX)
      CALL LCMPUT(IPSYS,'SPOT-Q-L2',1,4,QLAG_L2)
      CALL LCMPUT(IPSYS,'SPOT-Q-MAX',1,4,QLAG_MAX)
      CALL LCMPUT(IPSYS,'SPOT-FS-N',1,1,NFS_SNAP)
      CALL LCMPUT(IPSYS,'SPOT-REM-MIN',1,2,REMOVAL_MIN)
      CALL LCMPUT(IPSYS,'SPOT-REM-SNP',1,1,REMOVAL_SNAP)
      CALL LCMPUT(IPSYS,'SPOT-REM-GRP',1,1,REMOVAL_GROUP)
      CALL LCMPUT(IPSYS,'SPOT-REM-MIX',1,1,REMOVAL_MIX)
      IF(IMPX.GE.1) WRITE(IOUT,230) RBAL_MAX
      IF(IMPX.GE.1) WRITE(IOUT,235) QLAG_L2,QLAG_MAX
      IF(IMPX.GE.1.AND.IFIXB.EQ.1) WRITE(IOUT,237) RANK_POD
      IF(IMPX.GE.1) WRITE(IOUT,240) REMOVAL_MIN,REMOVAL_SNAP,
     1 REMOVAL_GROUP,REMOVAL_MIX
*
      DEALLOCATE(COEFF,BASIS,POD_SIG,POD_RANK,SIGMA)
      IF(ALLOCATED(VOLREF)) DEALLOCATE(VOLREF)
      DEALLOCATE(LEAK1D,DB2,VOLREG,PHIRK,SXSC,TXSC)
      DEALLOCATE(QFISS2D,SOUR2D,FLUX2D,FS_MODE)
      DEALLOCATE(VOL2D,MAT2D,IDL2D)
      RETURN
  200 FORMAT(' SPOASM: modal ranks across',I4,' groups: min=',I3,
     1 ', max=',I3,' (snapshot count=',I3,')')
  220 FORMAT(' SPOASM: physical S0 recovered for ',I0,
     1 ' snapshot-group systems')
  230 FORMAT(' SPOASM: max normalized radial balance=',1P,E11.4)
  235 FORMAT(' SPOASM: saved-RHS lag from selected RHS L2/max=',
     1 1P,2E11.4)
  237 FORMAT(' SPOASM: reused fixed POD basis with requested rank=',I3)
  240 FORMAT(' SPOASM: min effective removal=',1P,E11.4,0P,
     1 ' at snapshot/group/mixture=',3I6)
      END
